apiVersion: apps/v1
kind: Deployment
metadata:
  name: yubiwall
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: yubiwall
  template:
    metadata:
      labels:
        app: yubiwall
    spec:
      containers:
        - name: yubiwall
          image: rctl/yubiwall:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
          - name: YUBICO_CLIENT_ID
            value: "12345"
          - name: YUBICO_SECRET_KEY
            value: "xxxxxxxx"
          - name: ALLOWED_KEYS
            value: "xxxxxxxxxxxx,yyyyyyyyyy"


